"""Generated from spec/protocol-registry-v1.5.json; do not edit."""

REGISTRY_VERSION = '1.5.0'
BYTE_ORDER = 'big'

VERSION = 1
PRIVACY_PROFILE_U1 = 1
LIFECYCLE_PROFILE_E1 = 1
MESSAGE_PROFILE_M2 = 2
WIRE_PROFILE_W2 = 2
TRANSPORT_PROFILE_T1 = 3
SCHEDULE_PROFILE_T2 = 4

SUITE_C1_V1_RETIRED = b'\x00\x01'
SUITE_C2_SYMBOLIC = b'\x00\x02'
SUITE_C1_V2 = b'\x00\x03'
SUITE_R1 = b'\x01\x01'
SUITE_C2_K2_DISABLED = b'\x7f\x02'

MESSAGE_CHAFF = 0
MESSAGE_DISCOVER = 32
MESSAGE_CANDIDATE = 33
MESSAGE_COMMIT = 34
MESSAGE_READY = 35
MESSAGE_CANCEL = 36
MESSAGE_ABORT = 37
MESSAGE_CLOSE = 38
MESSAGE_RENDEZVOUS_OPEN = 39
MESSAGE_RENDEZVOUS_RESULT = 40
MESSAGE_DATA = 41

T1_FRAME_DATA = 0
T1_FRAME_ACK = 1
T1_FRAME_CHAFF = 2

T2_FRAME_SCHEDULE = 3

T2_ACTION_OFFER = 0
T2_ACTION_ACCEPT = 1
T2_ACTION_REJECT = 2

P1_PAYLOAD_GATEWAY_OFFER = 64
P1_PAYLOAD_RELAY_CANDIDATE_LAYER = 65
P1_PAYLOAD_COMMIT = 80
P1_PAYLOAD_READY = 81
P1_PAYLOAD_RENDEZVOUS_OPEN = 82
P1_PAYLOAD_RENDEZVOUS_RESULT = 83
P1_PAYLOAD_DATA = 84
P1_PAYLOAD_CLOSE = 85

ERROR_MALFORMED = 1
ERROR_UNSUPPORTED_VERSION = 2
ERROR_UNSUPPORTED_PROFILE = 3
ERROR_UNSUPPORTED_SUITE = 4
ERROR_AUTHENTICATION_FAILED = 5
ERROR_REPLAY = 6
ERROR_EXPIRED = 7
ERROR_RESOURCE_EXHAUSTED = 8
ERROR_STATE_VIOLATION = 9
ERROR_CAPABILITY_INVALID = 10
ERROR_TIMEOUT = 11
ERROR_CANCELLED = 12
ERROR_INTERNAL = 13

BYTES_SUITE_ID = 2
BYTES_BRANCH_TOKEN = 16
BYTES_CANDIDATE_TOKEN = 16
BYTES_LOCAL_LABEL = 16
BYTES_TRANSMISSION_ID = 16
BYTES_NEGOTIATION_ID = 16
BYTES_REPLY_PUBLIC_KEY = 32
BYTES_R1_DISCOVERY_NONCE = 32
BYTES_R1_CAPABILITY = 32
BYTES_GATEWAY_PSEUDONYM = 16
BYTES_ROUTE_SECRET = 32
BYTES_LINK_EPOCH = 4
BYTES_LINK_SEQUENCE = 8
BYTES_LINK_HEADER = 12
BYTES_LINK_TAG = 16
BYTES_CELL_BODY = 1024
BYTES_CELL_HEADER = 32
BYTES_CELL_PAYLOAD = 992
BYTES_CELL_RECORD = 1052
BYTES_REPLY_ENCAPSULATION = 32
BYTES_REPLY_AEAD_TAG = 16
BYTES_REPLY_KEY_COMMITMENT = 32

LIMIT_MAX_LOGICAL_MESSAGE_BYTES = 16384
LIMIT_MAX_CONTROL_PROTECTED_BYTES = 8192
LIMIT_MAX_FRAGMENTS = 17
LIMIT_MAX_REASSEMBLY_MESSAGES_PER_PEER = 64
LIMIT_MAX_REASSEMBLY_BYTES_GLOBAL = 131072
LIMIT_REASSEMBLY_TIMEOUT_MS = 1500
LIMIT_MAX_SENDER_TRANSMISSIONS_PER_PEER = 64
LIMIT_MAX_ROUTES_PER_PEER = 256
LIMIT_MAX_ROUTES_GLOBAL = 2048
LIMIT_MAX_CANDIDATE_LAYERS = 16
LIMIT_MAX_T1_RETRIES = 8
LIMIT_T1_RTO_MS = 100
LIMIT_REPLAY_WINDOW_CELLS = 1024
LIMIT_COMPLETION_CACHE_MS = 1000
LIMIT_ROUTE_TTL_MS = 5000
LIMIT_CAPABILITY_TTL_MS = 5000
LIMIT_MAX_FAILED_REDEMPTIONS_PER_ROUTE = 2

FIXED_T2_PROFILE_ID = 1
FIXED_T2_EPOCH_MS = 200
FIXED_T2_CELLS_PER_EPOCH = 16
FIXED_T2_SLOT_INTERVAL_US = 12500
FIXED_T2_ACK_RESERVE_PER_EPOCH = 4
FIXED_T2_RETRANSMIT_RESERVE_PER_EPOCH = 4
FIXED_T2_QUEUE_CELLS_PER_PEER = 256
FIXED_T2_QUEUE_CELLS_GLOBAL = 2048
FIXED_T2_MODE = 'fixed'

DOMAIN_C1_LABEL_PREFIX = b'Trahens-C1-v2'
DOMAIN_C1_SCALAR = b'Trahens-C1-scalar-v2'
DOMAIN_C1_ELEMENT = b'Trahens-C1-element-v2'
DOMAIN_C1_URE_R0 = b'Trahens-C1-ure-r0-v2'
DOMAIN_C1_URE_R1 = b'Trahens-C1-ure-r1-v2'
DOMAIN_C1_URE_S0 = b'Trahens-C1-ure-s0-v2'
DOMAIN_C1_URE_S1 = b'Trahens-C1-ure-s1-v2'
DOMAIN_C1_REPLY_EPHEMERAL = b'Trahens-C1-reply-ephemeral-v2'
DOMAIN_C1_CANDIDATE_AAD = b'Trahens-C1-candidate-layer-aad-v2'
DOMAIN_C1_CANDIDATE_INFO = b'Trahens-C1-candidate-layer-info-v2'
DOMAIN_C1_COMMIT = b'Trahens-C1-COMMIT-v2'
DOMAIN_C1_READY = b'Trahens-C1-READY-v2'
DOMAIN_C1_ACTIVE_TAG_SCALAR = b'Trahens-C1-active-tag-scalar-v2'
DOMAIN_C1_REPLY_COMMIT = b'Trahens-C1-reply-key-commitment-v2'
DOMAIN_W2_LINK_KEY = b'Trahens-W2-link-key-v1'
DOMAIN_R1_CAPABILITY = b'Trahens-R1-capability-v1'
DOMAIN_P1_ROUTE_KEY = b'Trahens-P1-route-key-v1'

FIELD_PROTECTION = {'link_epoch': 'public', 'link_sequence': 'public', 't1_frame_type': 'link-encrypted', 'm2_message_type': 'link-encrypted', 'm2_suite_id': 'link-encrypted', 'fragment_metadata': 'link-encrypted', 'branch_token': 'link-encrypted-hop-local', 'candidate_token': 'link-encrypted-hop-local', 'local_label': 'link-encrypted-hop-local', 'r1_discovery_nonce': 'link-encrypted-replaced-each-hop', 'gateway_pseudonym': 'end-to-end-encrypted', 'r1_capability': 'end-to-end-encrypted', 'route_secret': 'end-to-end-encrypted', 'application_data': 'end-to-end-encrypted', 'retransmission_counters': 'local-only', 'queue_depth': 'local-only', 'route_mapping': 'local-only', 'keys_and_capabilities': 'never-logged'}
