[package]
name = "trahens-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
links = "sodium"
build = "build.rs"

[dependencies]
protocol-registry = { path = "../protocol-registry" }

[lints]
workspace = true

[dev-dependencies]
test-vectors = { path = "../test-vectors" }
