#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate Python, Rust, and Markdown bindings from the frozen registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "spec" / "protocol-registry-v1.8.json"


def _name(value: str) -> str:
    return value.upper().replace("-", "_")


def _py_bytes(value: int, width: int) -> str:
    return repr(value.to_bytes(width, "big"))


def _series(data: dict[str, Any]) -> str:
    """Profile series, e.g. "1.7", taken from the registry being generated."""
    return ".".join(data["registry_version"].split(".")[:2])


def generate_python(data: dict[str, Any]) -> str:
    lines = [
        "# SPDX-License-Identifier: Apache-2.0",
        f'"""Generated from spec/protocol-registry-v{_series(data)}.json; do not edit."""',
        "",
        f'REGISTRY_VERSION = {data["registry_version"]!r}',
        f'BYTE_ORDER = {data["byte_order"]!r}',
        "",
    ]
    for key, value in data["protocol"].items():
        lines.append(f"{_name(key)} = {value}")
    lines.append("")
    for key, value in data["suites"].items():
        lines.append(f"SUITE_{_name(key)} = {_py_bytes(value, 2)}")
    lines.append("")
    # b1_record_types exists only from the v1.8 draft on; retained registries
    # regenerate without it, so every section lookup tolerates absence.
    for section, prefix in (
        ("message_types", "MESSAGE"),
        ("t1_frame_types", "T1_FRAME"),
        ("t2_frame_types", "T2_FRAME"),
        ("t2_schedule_actions", "T2_ACTION"),
        ("p1_payload_types", "P1_PAYLOAD"),
        ("b1_record_types", "B1_RECORD"),
        ("error_ids", "ERROR"),
        ("widths_bytes", "BYTES"),
        ("limits", "LIMIT"),
    ):
        entries = data.get(section, {})
        if not entries:
            continue
        for key, value in entries.items():
            lines.append(f"{prefix}_{_name(key)} = {value!r}")
        lines.append("")
    for key, value in data["fixed_t2_p1"].items():
        lines.append(f"FIXED_T2_{_name(key)} = {value!r}")
    lines.append("")
    for key, value in data["domain_separators"].items():
        lines.append(f"DOMAIN_{_name(key)} = {value.encode()!r}")
    lines.append("")
    lines.append(f"FIELD_PROTECTION = {data['field_protection']!r}")
    lines.append("")
    return "\n".join(lines)


def _rust_array(value: int, width: int) -> str:
    body = ", ".join(f"0x{byte:02x}" for byte in value.to_bytes(width, "big"))
    return f"[{body}]"


def generate_rust(data: dict[str, Any]) -> str:
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        f"// Generated from spec/protocol-registry-v{_series(data)}.json; do not edit.",
        f'pub const REGISTRY_VERSION: &str = "{data["registry_version"]}";',
        "",
    ]
    for key, value in data["protocol"].items():
        lines.append(f"pub const {_name(key)}: u8 = {value};")
    lines.append("")
    for key, value in data["suites"].items():
        lines.append(f"pub const SUITE_{_name(key)}: [u8; 2] = {_rust_array(value, 2)};")
    lines.append("")
    for section, prefix, ty in (
        ("message_types", "MESSAGE", "u8"),
        ("t1_frame_types", "T1_FRAME", "u8"),
        ("t2_frame_types", "T2_FRAME", "u8"),
        ("t2_schedule_actions", "T2_ACTION", "u8"),
        ("p1_payload_types", "P1_PAYLOAD", "u8"),
        ("b1_record_types", "B1_RECORD", "u8"),
        ("error_ids", "ERROR", "u16"),
        ("widths_bytes", "BYTES", "usize"),
        ("limits", "LIMIT", "usize"),
    ):
        entries = data.get(section, {})
        if not entries:
            continue
        for key, value in entries.items():
            lines.append(f"pub const {prefix}_{_name(key)}: {ty} = {value};")
        lines.append("")
    for key, value in data["fixed_t2_p1"].items():
        if isinstance(value, int):
            lines.append(f"pub const FIXED_T2_{_name(key)}: usize = {value};")
        else:
            lines.append(f'pub const FIXED_T2_{_name(key)}: &str = "{value}";')
    lines.append("")
    for key, value in data["domain_separators"].items():
        lines.append(f'pub const DOMAIN_{_name(key)}: &[u8] = b"{value}";')
    lines.append("")
    return "\n".join(lines)


def generate_markdown(data: dict[str, Any]) -> str:
    # The heading and source name follow the registry itself, so every retained
    # profile regenerates from its own file rather than one being frozen prose.
    series = _series(data)
    out = [
        "<!-- SPDX-License-Identifier: CC-BY-4.0 -->",
        "",
        f"# Trahens v{series} frozen protocol registry",
        "",
        f"> Generated from `protocol-registry-v{series}.json`; do not edit this file directly.",
        "",
        f"Registry version: `{data['registry_version']}`",
        f"Byte order for fixed-width integers: **{data['byte_order']}-endian**.",
        "",
    ]
    for title, section in (
        ("Suites", "suites"),
        ("Message types", "message_types"),
        ("T1 frame types", "t1_frame_types"),
        ("T2 frame types", "t2_frame_types"),
        ("B1 handshake record types", "b1_record_types"),
        ("Stable error identifiers", "error_ids"),
    ):
        entries = data.get(section, {})
        if not entries:
            continue
        out += [f"## {title}", "", "| Name | Decimal | Hex |", "|---|---:|---:|"]
        for key, value in entries.items():
            out.append(f"| `{key}` | {value} | `0x{value:04x}` |")
        out.append("")
    out += ["## Widths", "", "| Field | Bytes |", "|---|---:|"]
    for key, value in data["widths_bytes"].items():
        out.append(f"| `{key}` | {value} |")
    out += ["", "## Limits", "", "| Limit | Value |", "|---|---:|"]
    for key, value in data["limits"].items():
        out.append(f"| `{key}` | {value} |")
    out += ["", "## Fixed T2 P1 profile", "", "| Parameter | Value |", "|---|---:|"]
    for key, value in data["fixed_t2_p1"].items():
        out.append(f"| `{key}` | `{value}` |")
    out += ["", "## Field protection", "", "| Field | Classification |", "|---|---|"]
    for key, value in data["field_protection"].items():
        out.append(f"| `{key}` | `{value}` |")
    out += ["", "## C1 v2 domain separation", ""]
    for key, value in data["domain_separators"].items():
        out.append(f"- `{key}` = `{value}`")
    out.append("")
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--python-output", type=Path)
    parser.add_argument("--rust-output", type=Path)
    parser.add_argument("--markdown-output", type=Path)
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    args = parser.parse_args()
    data = json.loads(args.registry.read_text(encoding="utf-8"))
    targets = (
        (args.python_output, generate_python(data)),
        (args.rust_output, generate_rust(data)),
        (args.markdown_output, generate_markdown(data)),
    )
    for path, content in targets:
        if path is not None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
