[package]
name = "trahens-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
codec-m2 = { path = "../crates/codec-m2" }
link-handshake-b1 = { path = "../crates/link-handshake-b1" }
node-runtime = { path = "../crates/node-runtime" }
protocol-registry = { path = "../crates/protocol-registry" }
trahens-crypto = { path = "../crates/crypto" }
wire-w2 = { path = "../crates/wire-w2" }

[[bin]]
name = "m2"
path = "fuzz_targets/m2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "w2"
path = "fuzz_targets/w2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "b1"
path = "fuzz_targets/b1.rs"
test = false
doc = false
bench = false
